version: 2.1

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - run:
            name: Install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install
      - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
            name: Run tests
            command: |
                . venv/bin/activate
                make lint

workflows:
  default:
    jobs:
      - build-and-test
